title: beijinhos de algodão
author: lemuel roberto bonifácio
description: > # this means to ignore newlines until "baseurl:"
  olha só que céu lindo :D
baseurl: ""
twitter_username: lemuelroberto
google_analytics: UA-157522615-1
minima:
  date_format: "%b %-d, %Y"

exclude:
  - README.md
  - LICENSE.txt
  - Makefile
  - .gitignore
