title: Lemuel Roberto Bonifácio
author: Lemuel Roberto Bonifácio
description: > # this means to ignore newlines until "baseurl:"
  Olha só que céu lindo :D
baseurl: ""
twitter_username: lemuelroberto
github_username:  lemuelroberto

minima:
  date_format: "%b %-d, %Y"

exclude:
  - README.md
  - LICENSE.txt
  - Makefile
  - .gitignore
