title: beijinhos de algodão
author: lemuel roberto bonifácio
description: > # this means to ignore newlines until "baseurl:"
  poesias pra adoçar a alma ;)
baseurl: ""
twitter_username: lemuelroberto
google_analytics: UA-157565384-1
minima:
  date_format: "%b, %Y"

exclude:
  - README.md
  - LICENSE.txt
  - Makefile
  - .gitignore
